{% set name = "fsl-sub" %}
{% set version = "2.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fsl_sub-{{ version }}.tar.gz
  sha256: 5d843777416be2a16e5cec2bb0c4a68434f14c11ea64723d3b9658c841270321

build:
  entry_points:
    - fsl_sub=fsl_sub.cmdline:main
    - fsl_sub_config=fsl_sub.cmdline:example_config
    - fsl_sub_report=fsl_sub.cmdline:report_cmd
    - fsl_sub_plugin=fsl_sub.cmdline:install_plugin
    - fsl_sub_update=fsl_sub.cmdline:update
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - ruamel.yaml >=0.16.7

test:
  imports:
    - fsl_sub
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://git.fmrib.ox.ac.uk/fsl/fsl_sub
  summary: FSL Cluster Submission Script
  dev_url: https://git.fmrib.ox.ac.uk/fsl/fsl_sub
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pauldmccarthy
